- fonts/font.py
Found the bug: when a glyph is only 1 pixel wide, the for loop at line 124 doesn't do anything. I *think* line 141 was supposed to make up for this, but doesn't quite do it. (There's probably a more elegant solution than mine, but it works ;-)
All of the 2px+ glyphs remain exactly the same, and now the 1px glyphs are filled in as expected. Using the following to invoke font.py, you can see the first 2 glyphs (! and "):
```bash
python2 ./font.py -n profontiix_regular_10_72 -p build/profontiix_regular_10_72.png -x build/profontiix_regular_10_72.xml
```
```C
const uint8_t profontiix_regular_10_72_0x21[] __attribute__((__progmem__)) = {   /* '!' width: 6 */
0x03,          /* [*] */
0x03,          /* [*] */
0x03,          /* [*] */
0x03,          /* [*] */
0x03,          /* [*] */
0x03, …
```
> font.py: Fix issue w/ 1px wide characters

- fonts/font.py
Saves as much as 0.8k in some fonts
> font.py: Trim whitespace around glyphs

- source_code/src/FLASH/flash_test.c
- source_code/src/FLASH/flash_test.h
- source_code/src/OLEDMP/oledmp.h
While developing I used dmbs which added `-Wstrict-prototypes`. This showed up some warnings that I resolved.
> Fix some compiler warnings

- extension/background/event.js
This change bypasses the 'What domain do you want to store?' notifications if the multipass is not connected.
> bypass 'What domain..?' notifications if mooltipass not connected

- extension/background/event.js
This is difficult to reproduce, but the added code prevents the error message "Failed to send to device: Transfer failed" when the device is suddenly unplugged.
> Prevent "Failed to send to device: Transfer failed" error when device is suddenly unplugged

- source_code/src/stack.c
- source_code/src/stack.h
Might not work.
Other options:
* Disable optimization for this file
* [Do not compile stack.c with lto](https://stackoverflow.com/questions/25764582/is-it-possible-to-enable-link-time-optimization-while-only-disabling-strict-alia)
* Assembly
> Fixed lto bug with stackFree()

- source_code/src/GUI/mini_gui_basic_functions.c
- source_code/src/GUI/mini_gui_smartcard_functions.c
- "alt-beta vx.xx" version string for on-device creds management firmware
- text input cancellation bugfix: long press now works as intended when the field was filled with some text before cancellation
> Alt version string and text-input bugfix

- app/vendor/mooltipass/app.js
- app/vendor/mooltipass/emulator.js
- app/vendor/mooltipass/interface.js
- app/vendor/mooltipass/util.js
- extension/background/browserAction.js
- extension/vendor/mooltipass/device.js
emulator: added cancel code
interface: added a 'send' string to easily identify in console
util: added a checking for version (not related to task itself)
browserAction: added a check for the tab.id (sometimes it would throw a console error for tab id modified by chrome)
device: changed the call to onTabClosed from onTabUpdated. Now it goes: onTabUpdated -> onNavigatedAway -> onTabClosed.
device: Also commented out the timeout call (as I believe isn't needed anymore)
> app.js: added emulator part for cancel

- tools/_python_framework/Readme.md
Followup of #222.
Changes:
* Added udev link for linux -> removed dangerous sudo call of the tool
* Replaced `python mooltipass` with `./mooltipass`
* Added pacman command to Arch instruction
* Added section for other linux distributions
* Bundled linux instructions in its own section
You said my first instruction "did not work". What exactly did not work? You've added python2-crypto as dependency, but its already in the pip requirements list. So we can possibly remove the **distribution depenedency** to keep it consistent, as there is no user repository as on arch. This also allows to use the tool mostly on systems with no root rights if pip and python2 ist installed.
> Updated python tool readme for linux

- chrome_extension/manifest.json
- chrome_extension/mooltipass-content.js
- chrome_extension/vendor/mooltipass/moolticute.js
- chrome_extension/vendor/sendkeys.js
Sendkeys:
Changed the method we fill in fields, instead of setting the value for the input, we use a library that sends keystrokes, it works with input fields, contentEditable, and textareas. It also sends trusted events (by proxy as I saw in the code)
POST feature:
Some websites won't send a standard form submit but a XHR request, we intercept that and store credentials.
> Sendkeys + POST

- chrome_extension/vendor/mooltipass/mcCombinations.js
We need it because of manual credential storage
> Re-enable password generator icon for every form.

- source_code/src/OLEDMINI/oledmini.c
Fixes #261
As described in the issue already there were some display ghosting with the characters " ^ ' ` in some rare situations. It turned out that this was only the case for this very thin and high characters (compared to 0 for example), as the only use 3 pixel at the very top.
The problem was that the `miniOledBitmapDrawRaw()` did not take into account that sometimes you are only writing to a single page of the OLED (8 bits per page). In this case the MSB data will be kept (the part below the character) but the upper part will be trashed (LSB).
So in my special testcase if I want to write to position 0,3 a character with 3,5 size (^) it will keep all data below (0, 6-7 aka 0xC0) and trash all above (0, 0-2 aka 0x03). The magic here was to also keep the upper part and add 0xC0 to 0x03 …
> Fixed display ghosting on a single page

- chrome_app/vendor/mooltipass/device.js
Quick PR. works. Will be cleaning up and improving later.
Two major changes: 
1 - no more reconnecting web socket (we use our own version, tries to connect from 300ms to 3000ms)
2 - Added a few extra MS for reconnecting web socket. 
In high end computers, cpu usage stays at 1.5%
> Avoid quick "using moolticute" message.

- chrome_extension/mooltipass-content.js
Changed the val() usage in the password generator for sendkeys method. This method has proven effective and shouldn't affect the behavior at all. I also added a change event to be dispatched after the sendkeys command (as that's usually used by scripts to check that something has changed)
> Change val() usage for "send keys" in the password generator

- chrome_app/vendor/mooltipass/device.js
- chrome_extension/vendor/mooltipass/backend.js
- chrome_extension/vendor/mooltipass/moolticute.js
Device.js: 
1. Set usingMoolticute to false for obvious reasons
2. Start checking status by default (then stops when moolticute opens)
3. Avoid console output of commands meant for moolticute
Backend.js:
1. Small change in order to be able to track/debug status changes
Moolticute:
1. Just change status when we're using moolticute. Leave status to standard method when using the APP
> Fix blinking icon / Fix reconnection when closing moolticute

- tools/_python_framework/mooltipass_tool.py
- tools/_python_framework/signing_and_uploading_your_own_firmware.txt
Added a script option to generate the necessary bundle upload password needed to upgrade you MPM with an official or custom firmware.
Requires a plugged MPM, AES Key 2 and UID Request Key.
Although the key could be generated "offline", it's safer to require plugging the MPM to automatically retrieve the current firmware version and UID.
> Add script option to generate bundle upload password

- chrome_extension/vendor/mooltipass/moolticute.js
Fixes: 
Open a tab with a prompt request, then close it without approving nothing
Then open again a new tab
You will not get the prompt on the device
> Fix bug on 2nd request after a cancel

- source_code/src/mooltipass.c
Fixes FW compilation issues.
When compiling, -Werror=unused-but-set-variable triggers a warning with DISABLE_FUNTIONAL_TEST because mini_inputs_result isn't used anymore. This fixes it.
> Fix -Werror=unused-but-set-variable on mini_inputs_result

- source_code/src/GUI/mini_gui_smartcard_functions.c
- source_code/src/defines.h
- source_code/src/mooltipass.c
- source_code/src/mooltipass.h
New feature allowing to boot the mini with the wheel pressed and set a flag accordingly. 
- Adds define layout and meta-defines for hardening purposes.
- Also adds defines for pre-production and ks models (4Mb/8Mb flash).
- Finally, adds a custom version string to visually identify devices with a different firmware from stock devices.
> Feature: Button at boot and hardening

- source_code/src/USB/usb_cmd_parser.c
- source_code/src/defines.h
This PR adds a define to optionally remove CMD_CHECK_PASSWORD which allows silent password checking over USB against the database.
> Hardening: disable "silent" password check over USB

- source_code/src/USB/usb_cmd_parser.c
- source_code/src/defines.h
- source_code/src/mooltipass.h
Adds an optional restriction to memory management mode, only allowing the transition if the device has been booted with the wheel pressed.
Also fixes flag variable export.
> Hardening: Restrict memory management mode

- source_code/src/USB/usb_cmd_parser.c
- source_code/src/defines.h
- source_code/src/mooltipass.h
Adds a define to optionally remove the CMD_GET_RANDOM_NUMBER command.
Also adds comments in define.h about the size freed/used by these hardening features
> Hardening: Disable usb cmd rng

- source_code/Makefile
Fixes #348 
Current state of the Makefile is unable to build bootloader properly.  This commit removes some test sources that were matched and making the resulting binary too large.  Also adds a define for building the bootloader, correctly names the bootloader map file, and allows BOOTLOADER= to be specified on the command line.
> Changes to allow building of bootloader correctly

- chrome_extension/Mooltipass.safariextension/Info.plist
- chrome_extension/popups/js/popup_status.js
Added check for existence of mooltipassEvent.
Background page is loaded in the separate thread.
If we try to access to mooltipassEvent when it is not loaded, then
updating of status is broken.
> Fix updating the device status

- chrome_extension/mooltipass-content.js
- chrome_extension/vendor/mooltipass/mcCombinations.js
There were two problems:
1. detectCombination didn't find dynamically created inputs after inputs hash is changed. I didn't figure out exactly why this happens, simple setTimeout solved this issue. Need more time to understand it, or maybe you can help with advice.
2. And the main problem is that onSubmit handler didn't trigger when we try to authorize for the first time. I added code to handle events ("Next" button click and pressing return key in input) to handle submit explicitly.
> fix google authorization

- chrome_extension/updateCleanVersion.sh
When run with --emulation-mode this set the boolean to true under
device.js.
This is related to PR #432
> <chrome_extension/pkg builder: Add flag>

- chrome_extension/updateCleanVersion.sh
Document how to use this flag.
Related to PR #433 where documentation about the added flag was missing on the usage output.
> chrome_extension/pkg builder: Provide document about emulation mode>

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Patreon.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/esp8266.java
> fixed esp and patreon

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/config/WebDriverFactory.java
> added public restricted mode

- chrome_extension/background/event.js
- chrome_extension/background/httpauth.js
- chrome_extension/background/init.js
- chrome_extension/manifest.json
- chrome_extension/mooltipass-content.css
- chrome_extension/mooltipass-content.js
- chrome_extension/vendor/mooltipass/device.js
Finally got it working for both Chrome and Firefox!
* In emulation mode callback for _mooltipass.device.retrieveCredentials_ didn't execute that's why there was no auth popup.
* Stuck with a problem that it's impossible to get `Authorization` header while we intercept response. But we can create our custom popup and handle http authorization by ourself. I used window.prompt now, will add popup later.
* Firefox doesn't execute callback because of the _asyncBlocking_ setting. It's not supported and I will see the differences between Chrome's _asyncBlocking_ and Firefox's _blocking_.
> handle http auth

- chrome_extension/vendor/mooltipass/mcCombinations.js
> don't override credentialsCache with empty value

- chrome_extension/background/init.js
- chrome_extension/vendor/mooltipass/mcCombinations.js
New _doSubmit_ implementation. Now we focus on buttons for submitting forms with more flexible detection by adding `ACCEPT_PATTERNS` and `IGNORE_PATTERNS`. Also there is a fix for missing post requests from previous pull request.
Tested on the recently reported sites:
* https://web.tresorit.com/login
* https://www.vodafone.de/ussa/login/login.ftel
* https://nordinary-com.netcup-mail.de/SOGo/
* https://accounts.google.com/ServiceLogin
Also setting tests now.
> revisited submit and missing form data

- chrome_extension/vendor/mooltipass/device.js
- chrome_extension/vendor/mooltipass/mcCombinations.js
Added some code the enable auto-login for the Trillian site: [trillian.im/web/4.0/](trillian.im/web/4.0/).
Overview of the modifications:
1) Add an extended combination to handle: the detection of entered credentials + auto-login.
2) Add a custom combination to leverage the extended combination.
3) Within the retrieve credentials callback, look for the custom auto-login function to invoke it if exists instead of run the usual procedure.
> Extension for Trillian support

- chrome_extension/mooltipass-content.js
On some services (airbnb.com, dropbox.com) we initialize inside user targeting iframes or captchas. This leads to obsessive amount of credential requests and post request detections.
> don't initialize in user targeting iframes

- chrome_extension/mooltipass-content.css
Discovered this issue on komoot.de – we calculate position for tooltip based on viewport dimensions and if page isn't scrolled to top tooltip will be at wrong position.
> fix position for password popover

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Anibis.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/GitHub.java
> fixed anibis and github

- sauce_labs_tests/src/test/resources/mooltipass/automatedTest/features/Supported.feature
> fixed hackaday

- chrome_extension/background/event.js
- chrome_extension/background/httpauth.js
- chrome_extension/http-auth.html
- chrome_extension/mooltipass-content.css
- chrome_extension/mooltipass-content.js
Haven't got working HTTP Auth for proxy in firefox, somehow handler doesn't execute. But web http auth works well.
Test cases:
1. HTTP Auth for web service with direct link
* Go to push.org.ru/grisha/auth/success
* Redirecting to _http-auth.html_
* Enter credentials (me:me)
* Credentials should be saved for auth url
* Redirecting to succes page
2. HTTP Auth for web service with indirect link
* Go to push.org.ru/grisha/auth
* Click AUTH button
* Redirecting to _http-auth.html_
* Enter credentials (me:me)
* Credentials should be saved for auth url
* Redirecting to success page
3. HTTP Auth for proxy
* Set proxy in settings
* Open any url
* Redirecting to _http-auth.html_
* Enter credentials
* Credentials should be saved for proxy address
* Redirecting to the previous url
> revisited http auth

- chrome_extension/background/httpauth.js
There was an issue with Chrome – HTTP Auth request executed before we update information about tabs, that's why request was cancelled when we try to open link from bookmarks bar in a new tab.
> cancel requests which are initiated not from tabs

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/DropBox.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Komoot.java
> fixed dropbox and komoot

- chrome_extension/mooltipass-content.js
- chrome_extension/vendor/mooltipass/mcCombinations.js
* issue with id field with special symbols, password generator didn't show up in this case
* issue when we change fields in selection, but mcCombs still used old ones
* removed trillian extended combination and sendkeys for login (somehow it caused site scripts to clear password field)
* added soundcloud support for 2-step auth
* change how detectSubmitButton works: find buttons near field and go to the top, compare distance based on viewport position
* compare distance between button and password field, not login field
> sites compatibility

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/GitHub.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Microspot.java
- sauce_labs_tests/src/test/resources/mooltipass/automatedTest/features/Supported.feature
> github and microspot fixed

- chrome_extension/Mooltipass.safariextension/Info.plist
- chrome_extension/background/event.js
- chrome_extension/background/init.js
- chrome_extension/mooltipass-content.js
- chrome_extension/ui/custom-credentials-selection/custom-credentials-selection.html
- chrome_extension/ui/http-auth/http-auth.html
- chrome_extension/ui/password-dialog-toggle/password-dialog-toggle.css
- chrome_extension/ui/password-dialog-toggle/password-dialog-toggle.html
- chrome_extension/ui/password-dialog-toggle/password-dialog-toggle.js
- chrome_extension/ui/password-dialog/password-dialog.html
- chrome_extension/updateSafariExtension.sh
Fixed issue with unsupported `getURL` method in Safari and problems with relative paths in UI. And we can't prevent default HTTP Auth process, it's just not supported in Safari.
> safari compatibility

- chrome_extension/manifest.json
I have removed `contentSettings` permission. It's valid in Chrome, but we don't use this API anyway. For jQuery it seems to be a mistake with hash on testers side, I got exactly the same checksum that supposed to be valid:
```
➜  chrome_extension git:(master) shasum -a 256 vendor/jquery-3.2.1.js
0d9027289ffa5d9f6c8b4e0782bb31bbff2cef5ee3708ccbcb7a22df9128bb21  vendor/jquery-3.2.1.js
```
> pass mozilla validation

- chrome_extension/background/browserAction.js
- chrome_extension/background/event.js
- chrome_extension/background/init.js
- chrome_extension/background/page.js
- chrome_extension/popups/js/popup_status.js
- chrome_extension/vendor/mooltipass/device.js
Test scenario for tab closing:
1. Open page with saved credentials
2. See notification on the device
3. Close tab
4. Notification should disappear on the device
Test scenario for tab focusing:
1. Open page with saved credentials
2. Move to another tab
3. Move back
4. Notification should appear on the device
> support tab focus and close event in Safari

- chrome_extension/mooltipass-content.js
- chrome_extension/ui/password-dialog/password-dialog.js
- chrome_extension/vendor/mooltipass/mcCombinations.js
Open _skype.com, soundcloud.com, google.com, etc_ services with two page auth and discover that `Select custom credential fields` isn't available in password dialog.
> hide custom credentials for two page auth

- chrome_extension/vendor/mooltipass/device.js
1. Connect locked device
2. Refresh page in browser
3. See that notification shows up
4. Refresh page again
5. See that notification doesn't show up
6. Reconnect device
7. Refresh page
8. See that notification shows up
> reenable notifications when device is connected

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/EBay.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/GitHub.java
> fixed failing websites

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Ricardo.java
> updated Ricardo pageobjects class

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Firefox.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Minfin.java
> fixed firefox and minfin tests

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/EBay.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Microspot.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/TurkishAirlines.java
> microspot, turkish airlines and ebay fixes of tests

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Microspot.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/PcbWay.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/TurkishAirlines.java
> fixed pcb, turkishairlines and microspot tests

- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/AbstractPage.java
- sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Microspot.java
> fixed microspot test

- sauce_labs_tests/.classpath
- sauce_labs_tests/.settings/org.eclipse.jdt.core.prefs
- sauce_labs_tests/pom.xml
> fixed config error for tests
