limpkin/mooltipass

fonts/font.py
Reverts limpkin/mooltipass#143
=> Revert "font.py: Fix issue w/ 1px wide characters"

.gitmodules, fonts/characters.txt, fonts/readme.md
Used git submodule to add fontbuilder to project, and wrote up instructions on how to use it to regenerate fonts.
It'd be nice to extend fontbuilder to support scripted operation so we don't have to store intermediate files in the repository, but this is a good first step. ;-)
=> Integrate fontbuilder with instructions for regenerating fonts

extension/background/init.js, extension/mooltipass-content.js, extension/options/js/options.js, extension/popups/js/popup_status.js, extension/popups/popup.js, extension/popups/popup_functions.js, extension/popups/popup_remember.js, extension/vendor/mooltipass/device.js, extension/vendor/mooltipass/website.js
chrome.extension messaging API is deprecated and chrome.runtime should
be used instead.
Some info: https://bugs.chromium.org/p/chromium/issues/detail?id=495052
=> Update deprecated chrome.extension API to runtime

source_code/src/AES/aes256_ctr.c
Fix some spaces.
I might have missed some, did not look into the other files yet.
=> Style fixes

app/html/jade/_in_mmm_error.jade, app/html/jade/_not_in_mmm_error.jade
Changed 'Memory Management Mode' to 'Credentials Management Mode' in Jade templates.
=> App template updates

app/vendor/mooltipass/emulator.js, extension/mooltipass-content.js
Also added a return for empty credentials
=> Fix for success true/false

bitmaps/mini/fw_strings.txt, source_code/src/GUI/mini_gui_basic_functions.c, source_code/src/GUI/mini_gui_basic_functions.h, source_code/src/GUI/mini_gui_credentials_functions.c, source_code/src/GUI/mini_gui_credentials_functions.h, source_code/src/GUI/mini_gui_screen_functions.c, source_code/src/LOGIC/logic_aes_and_comms.c, source_code/src/LOGIC/logic_aes_and_comms.h, source_code/src/LOGIC/logic_fwflash_storage.h, source_code/src/NODEMGMT/node_mgmt.c, source_code/src/NODEMGMT/node_mgmt.h, source_code/src/defines.h
Adds support for on-device credential creation/edition/renewal/deletion.
Fixes minor bugs.
Integer entry features:
- proposed value starts at the max boundary allowed;
- a short click will confirm the selected value;
- a long click will cancel the input.
Text entry features:
- proposed character starts with 'A';
- any wheel click flashes the screen;
- a short click selects a character;
- a long click erases the previous character;
- "ENTRY_LONGCLICK_ERASE" (2) long clicks in a row clear the input field;
- a long click with an empty field cancels the input;
- 3 "special" characters provide alternative confirmation methods:
- ENTRY_CHAR_OK_STR ("OK"): confirms text input,
- ENTRY_CHAR_CANCEL_STR ("XX"): cancels text input,
- ENTRY_CHAR_BACKSPACE_STR ("<-"): erases the previous character;
- …
=> New feature: on-device credential management/generation + minor bugfixes

tools/_python_framework/Readme.md, tools/_python_framework/requirements.txt
=> Updated python tool readme + added pip instructions

app/vendor/mooltipass/emulator.js, extension/mooltipass-content.js
Changes in cipDebug: So it shows the line number in the console
Added a more sophisticated method to detect forms
Changed the timeout to retrieve credentials to 1 sec.
=> First integration of detection by rules.

source_code/src/LOGIC/logic_aes_and_comms.c, source_code/src/NODEMGMT/node_mgmt.c
Fixes compilation issues with on-board credential management due to https://github.com/limpkin/mooltipass/commit/0e17d9d57391f324b1b76d00c8d467dc50378da2 and fixes a minor naming conflict with a global identifier.
Tested on MPM alu with accelerometer.
=> Fixes cNode buffer related changes

extension/mooltipass-content.js
Adds compatibility to Linked-in (not in a specific way)
=> Linked in compatibility

extension/mooltipass-content.js
=> Mac and PC compatibility for linkedin

chrome_extension/background/event.js, chrome_extension/background/init.js, chrome_extension/background/page.js, chrome_extension/css/pages.css, chrome_extension/css/popup.css, chrome_extension/manifest.json, chrome_extension/mooltipass-content.js, chrome_extension/options/js/options.js, chrome_extension/options/options.html, chrome_extension/popups/js/popup_status.js, chrome_extension/vendor/mooltipass/backend.js, chrome_extension/vendor/mooltipass/device.js, chrome_extension/vendor/mooltipass/moolticute.js, chrome_extension/vendor/mooltipass/website.js, chrome_extension/vendor/reconnecting-websocket.js
Adjusted parameters to be Firefox Compatible, implementation for moolticuted.
=> firefox compatibility

source_code/src/LOGIC/logic_aes_and_comms.c
As discussed on IRC, minor fix.
=> Used USER_CTR_SIZE definition for dataNoteCtrVal

chrome_extension/background/init.js, chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/device.js, chrome_extension/vendor/mooltipass/moolticute.js
Several issues fixed:
Most important:
Use queue instead of skip it with moolticuted
Send cancel requests
Added more combinations (and moved to the object scope instead of function)
Try to get credentials from POST requests when the onSubmit fails to do so.
=> Several issues fixed

chrome_extension/background/event.js, chrome_extension/mooltipass-content.css, chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/moolticute.js
a) Icon for FF
b) Fixes for FF 49
c) Some translations from debugLog to log
=> Firefox fix for not starting automatically on Version 49. (also icon)

source_code/src/FLASH/README.md
Verified in datasheet and your excel sheet on google docs.
=> Update FLASH README.md

chrome_extension/background/init.js, chrome_extension/mooltipass-content.js
Sending PR, refactored a bit the combination structure. So, I need to fully test in several scenarios before feeling confident for release!
=> Bank of America support (not for release yet!)

chrome_extension/manifest.json, chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/device.js, chrome_extension/vendor/mooltipass/mcCombinations.js
A lot of changes in this PR!
Now we use mcCombinations as a primary resource for form detection.
=> Updated Extension to use mcCombinations

chrome_extension/vendor/mooltipass/moolticute.js
Fixes request_id sent to moolticute for cancel_request.
=> fix request_id that is sent to moolticute for cancel_request

chrome_extension/vendor/mooltipass/moolticute.js
request_id in cancel request must be wrapped in the data field.
=> cancel_request data must be in .data field

chrome_extension/background/event.js, chrome_extension/background/httpauth.js, chrome_extension/vendor/mooltipass/mcCombinations.js
Http and https logins now working again.
While I kept the "event" variable, I renamed it to mooltipassEvent. It is recommended to migrate all uses of event. to mooltipassEvent in the near future.
=> HTTP Login Update

chrome_extension/background/event.js, chrome_extension/background/init.js, chrome_extension/background/page.js, chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/backend.js, chrome_extension/vendor/mooltipass/mcCombinations.js, chrome_extension/vendor/mooltipass/moolticute.js
1 - Make dropbox work
2 - Porting debug method to background scripts (just started)
3 - Bug fixes on double requests
4 - Clean some error messages
5 - Password retrieval improvements
=> Password reset procedures + others

fonts/font.py, fonts/font_mini.py
Adds python2 to the shebang as described in the readme. Using python3 won't work. Also chmod +x the mini script, as the normal one also is.
=> Fixed font tool start under linux

chrome_extension/background/event.js, chrome_extension/vendor/mooltipass/device.js, chrome_extension/vendor/mooltipass/mcCombinations.js
Adds support to << redacted >> by using the old loose method.
=> Start old method if main method fails to detect.

bitmaps/mini/bundle.py, bitmaps/mini/imagetoimg.py
Fixes phython2 shebang and execution permission for linux
=> Fixed bundle tools for linux

chrome_extension/background/httpauth.js, chrome_extension/vendor/mooltipass/mcCombinations.js, chrome_extension/vendor/sendkeys.js
Support to fill (and not submit) forms with 3 fields.
=> Key-up and new combination

chrome_extension/background/page.js, chrome_extension/vendor/mooltipass/device.js, chrome_extension/vendor/mooltipass/mcCombinations.js
=> Password reset.

chrome_app/vendor/mooltipass/device.js
=> App -> Don't connect to the device if moolticute is running.

chrome_extension/vendor/mooltipass/mcCombinations.js
Quick fix to support adobe.com
=> Adobe Support

chrome_extension/mooltipass-content.js
Fixes issue with Password generator
=> Password generator fix

chrome_extension/background/event.js, chrome_extension/background/init.js, chrome_extension/background/page.js, chrome_extension/popups/js/popup_status.js
Fixes issue with Password generator
=> Fix for FF50

chrome_extension/background/event.js, chrome_extension/background/init.js, chrome_extension/background/page.js
Fix for Chrome intermittent error
=> Should work now?

chrome_extension/options/options.html, chrome_extension/popups/js/popup_status.js, chrome_extension/updateCleanVersion.sh, chrome_extension/vendor/mooltipass/device.js, chrome_extension/vendor/mooltipass/mcCombinations.js, chrome_extension/vendor/mooltipass/moolticute.js
As the title says. Initial commit. Need to test deeper.
=> Extension Side for auto moolticute/app switch

chrome_app/vendor/mooltipass/device.js
1 - Open moolticute
2 - Install App
3 - Close moolticute.
=> Listen for onclose for the next scenario:

chrome_extension/background/init.js, chrome_extension/vendor/mooltipass/device.js
1 - no error in the console when opening a new tab 
2 - scenario: moolticute -> app -> ext working now.
=> 2 out of 3

chrome_extension/background/event.js, chrome_extension/background/init.js, chrome_extension/popups/js/popup_status.js, chrome_extension/vendor/mooltipass/mcCombinations.js, chrome_extension/vendor/mooltipass/moolticute.js
Requires Moolticute +0.5.2 for the open app to work.
=> Open APP / Google Login

chrome_extension/background/page.js, chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/mcCombinations.js
Do not merge yet, need 1 more commit
=> Update password update procedures to match latest version

chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/mcCombinations.js
=> Yahoo login (et more)

chrome_extension/manifest.json, chrome_extension/vendor/mooltipass/backend.js, chrome_extension/vendor/mooltipass/device.js
Fixes fails on loading the extension components in windows
=> Adjust loading order

chrome_extension/background/browserAction.js, chrome_extension/background/event.js, chrome_extension/background/init.js, chrome_extension/manifest.json, chrome_extension/mooltipass-content.js, chrome_extension/popups/js/popup_status.js, chrome_extension/vendor/jquery-ui-1.11.4.custom/jquery-ui.js, chrome_extension/vendor/mooltipass/backend.js, chrome_extension/vendor/mooltipass/moolticute.js, chrome_extension/vendor/mooltipass/website.js
Remove console.log from several files
Move jQuery-ui below website.js for "jQuery.noConflict" chance to load before jQuery-ui does.
=> Remove Console Logs

chrome_extension/updateCleanVersion.sh
With the [PR #321 ](https://github.com/limpkin/mooltipass/pull/321) I also provide some change to the script for building browser extension that handle firefox/chromium.
=> <extension/updateCleanVersion: Provide a way to package web extension>

chrome_extension/install.rdf
It seems that XPI file are expecting some install.rdf to get meta data on the extension/theme... This is a proposition of such file for Mooltipass extension for Firefox.
=> <firefox_extension: Provide an install.rdf to package with XPI>

chrome_app/html/scss/_layout.scss, chrome_app/html/stylesheets/app.css, mooltiapp/app/main.js
Window isn't resizable anymore.
=> Remove black bar

chrome_app/html/stylesheets/mooltiapp.css, mooltiapp/app/main.js, mooltiapp/app/preload.js
Also, load a new CSS in Chrome_APP when is loaded within mooltiapp
=> Aesthetic change

mooltiapp/app/preload.js
To reproduce:
1 - Save wrong credentials for a site that redirects to the same page on failure.
2 - Open site on Chrome, you'll get request after request on login/fail/login for that site.
3 - Open site on Safari, you'll get request after request on login/fail/login for that site.
=> Fix strange bug on Safari/Chrome working together.

chrome_app/html/js/credentials.js, chrome_extension/mooltipass-content.css, chrome_extension/mooltipass-content.js
Fixes #345 
By adding a mp-dialog class to the jquery ui dialog we avoid overwriting other websites.
=> Fix for issue 345

chrome_extension/background/init.js, chrome_extension/mooltipass-content.css, chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/mcCombinations.js, chrome_extension/vendor/mooltipass/moolticute.js
When selecting the login / password field, it seems the new selection is not taken into account when hovering the "store or update current credentials" part.
Fixed some oddities as well
Autodesk Combination (99% done)
=> Bug fixing 

chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/mcCombinations.js
e.stopPropagation(); works in password change popups that have a onclick elsewhere hide (linked-in and trello)
extendedPost: bridges posts sent by ajax in some sites to something we can understand, as that's something arbitrary from their developer, there's no reliable way to do it.
some other changes as well
=> Site compatibility adds

source_code/src/GUI/mini_gui_basic_functions.c, source_code/src/GUI/mini_gui_smartcard_functions.c, source_code/src/defines.h, source_code/src/mooltipass.c
Adds define to optionally remove the screensaver from the code.
Also added to hardening meta-define.
=> Hardening/cleanup: Disable screensaver

source_code/src/GUI/mini_gui_basic_functions.c, source_code/src/GUI/mini_gui_smartcard_functions.c, source_code/src/defines.h, source_code/src/mooltipass.c
Reverts limpkin/mooltipass#354
=> Revert "Hardening/cleanup: Disable screensaver"

chrome_extension/vendor/mooltipass/device.js, chrome_extension/vendor/mooltipass/moolticute.js
And queue empties when there's a disconnection from moolticute or mooltiapp
=> Fix intermittent recursion error

chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/mcCombinations.js, chrome_extension/vendor/mooltipass/moolticute.js
Will fill in comments in the next commit
=> Mid-commit for code review

chrome_extension/mooltipass-content.css, chrome_extension/mooltipass-content.js
=> Getting rid of jQuery-UI

chrome_extension/manifest.json, chrome_extension/mooltipass-content.css, chrome_extension/mooltipass-content.js
Removed some unused code as well
=> Cleanup for previous PR

chrome_extension/vendor/mooltipass/device.js, chrome_extension/vendor/mooltipass/moolticute.js
This solves the problem on starting mooltiapp after a credential request has been stored
(and it is 1 step forward a more serious queue management in the extension side)
=> Process Queue when mooltiapp comes alive

chrome_extension/mooltipass-content.js
Fixed issue #387 by preventing Password Generator Dialog from being created multiple times.
- [x ] This PR is compliant with the contributing guidelines (if not, please describe why): code is fully documented and if possible a .md file is made.
- [ x] The PR text includes a **detailed explanation** (more than 50 chars)
- [ x] I have thoroughly tested my contribution.
=> Fixes Issue 387

chrome_extension/Mooltipass.safariextension/Info.plist
Updated bundle identifier
Removed missed css styles file
Added «Update From Gallery» config
=> Fix info.plist

chrome_extension/popups/js/popup_status.js
Close popup when user click on any item on Safari.
=> Fix popup closing

chrome_extension/background/event.js, chrome_extension/popups/js/popup_status.js
Now site can be added to blacklist or removed from blacklist in the
popup on Safari.
=> Fix blacklist feature in popup on Safari

chrome_extension/vendor/mooltipass/mcCombinations.js
"Show password" button on paypal was detected as submit button.
=> [ci-ext] ignore pattern for paypal

chrome_extension/css/pages.css, chrome_extension/options/js/options.js, chrome_extension/scss/pages.scss
Somehow chrome doesn't load font awesome font.
=> replace font icon with inlined svg

chrome_extension/vendor/mooltipass/mcCombinations.js
Following fixes:
* Ignore patterns for wrong submit button detection
* Don't autosubmit form when two-factor auth is presented
* Intercept click event on submit button to trigger onSubmit handler
=> Steam support

chrome_extension/vendor/mooltipass/mcCombinations.js
Fixed compatibility issues for sites:
* ldlc.ch
* techmania.ch
* evernote.com
* tripadvisor.com
Auth works by manual testing. @mosaadm take a look if we should fix our automated tests.
=> sites compatibility

sauce_labs_tests/src/test/java/mooltipass/automatedTest/features/TurkishAirlinesSteps.java, sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/AirBnB.java, sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Anibis.java, sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/Gmail.java, sauce_labs_tests/src/test/java/mooltipass/automatedTest/pageObjects/TurkishAirlines.java, sauce_labs_tests/src/test/resources/mooltipass/automatedTest/features/NotSupported.feature
=> added turkish airlines, fixed airbnb gmail and anibis

chrome_extension/vendor/mooltipass/backend.js
Changes for #465 issue.
@limpkin I have added only `vmbuild` as allowed local domain.
=> add vmbuild to local domain

chrome_extension/vendor/mooltipass/mcCombinations.js
=> ignore searh field in getAllForms

chrome_extension/vendor/mooltipass/mcCombinations.js
=> different field for two-factor auth for Steam with mobile code

chrome_extension/vendor/mooltipass/backend.js
We have another issue with local domain – https://mynas:7777. Maybe we can consider removing this validation.
=> allow local domains

chrome_extension/mooltipass-content.js, chrome_extension/ui/password-dialog/password-dialog.js
=> check for dialog on hide and on selection show, pass window dimensions

chrome_extension/background/init.js, chrome_extension/mooltipass-content.js, chrome_extension/vendor/mooltipass/mcCombinations.js
I've removed detection based on regexp for loaded scripts. Now we check element's  class which match *captcha* keyword.
For _minfin.com.ua_ we still detect captcha because it's visible, but overlapped by overlay.
=> captcha detection

chrome_extension/vendor/mooltipass/mcCombinations.js
* don't treat password restore form as login form for evernote
* don't fill password for forms without password confirmation
* save password for google password restore
=> password restore improvements

chrome_extension/ui/password-dialog/password-dialog.css, chrome_extension/ui/password-dialog/password-dialog.js
Check that password dialog doesn't exceed top window boundary and viewport height.
Issue on https://www.leroymerlin.fr
=> overflow password dialog

chrome_extension/ui/custom-credentials-selection/custom-credentials-selection.js
these changes removes additional fields that appeared after username and password selected
=> remove markAllStringFields

README.md
The description talks about Mooltipass Mini but the link leads to the regular Mooltipass. I have updated the link for consistency.
=> update link to Mooltipass Mini
